version: "2"

services:
    postgres:
        image: postgres:10
        restart: always
        ports:
            - '6002:5432'
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_HOST: postgres
            POSTGRES_DB: refl
        volumes:
            - postgres:/var/lib/postgresql/data
    app:
        build:
            context: . 
            dockerfile: Dockerfile
        ports:
            - '8080:8080'
        
volumes:
    postgres: ~
    